sudo: required
branches:
  only:
  - gh-pages
language: bash
services:
  - docker
before_install:
  - make
script:
  - docker-compose up -d postgres
  - sleep 10
  - docker-compose run import-swisstopo
  - docker-compose run db-schema
  - docker-compose run export-geojson
